services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8090
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
    env_file:
      - .env
    depends_on:
      - service-b
      - otel-collector
    networks:
      - otel-network

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - VIACEP_API_URL=${VIACEP_API_URL}
      - WEATHERAPI_URL=${WEATHERAPI_URL}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
    env_file:
      - .env
    depends_on:
      - otel-collector
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "55681:55681"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - otel-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - otel-network

networks:
  otel-network:
