version: "3.8"

services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - service-b
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=service-a
    networks:
      - tracing

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=service-b
    networks:
      - tracing
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "55680:55680"
    networks:
      - tracing

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - tracing

networks:
  tracing:
    driver: bridge